#we need to use pyprocar, make sure that you have this module before running this file
#we need to use POSCAR and KPOINTS to generate this file, you can also set it by yourself
#we have POSCAR under the standard of Materials Project, it could be wrong if not under that standard
#we have KPOINTS under the standard generated by vaspkit, it could be wrong if not under that standard
#the basic frame was written by my senior \phq/(thanks), hope this file can help you ^_^
#-------------------------------------#
import pyprocar 
#-------------------------------------#
Emin=-1
Emax=1
cmap='hot_r'
knames=['G', 'X', 'W', 'K', 'G', 'L', 'U', 'W', 'L']
kticks=[0, 20, 40, 60, 80, 100, 120, 140, 160]
discontinuities=[]
#-------------------------------------#
pyprocar.repair('PROCAR','PROCAR-band')
#-------------------------------------#
title='D03_bandstructure'
pic = pyprocar.bandsplot(dirname='../SOC',code='vasp',title=title,fermi=6.44,elimit=[Emin,Emax],mode='plain',spins=[0],knames=knames,kticks=kticks,opacity=[1.0],linestyle=['dashed'],color='gray',fermi_linestyle='solid',fermi_color='green',fermi_linewidth=1,print_plot_opts=True,dpi=100,show=False,figure_size=[15,6],linewidth=[2])
pyprocar.bandsplot(dirname='.',code='vasp',title=title,fermi=6.44,elimit=[Emin,Emax],mode='plain',spins=[0,1],spin_colors=['blue','red'],knames=knames,kticks=kticks,linestyle=['solid','solid'],opacity=[1.0,1.0],linewidth=[2,2],fermi_linestyle='solid',fermi_color='green',fermi_linewidth=1,ax=pic[1],dpi=300,savefig="bandspin.png")

